#项目名称
rabbitchat:
  #项目中文名
  name: 兔叽Chat
  #项目英文名
  nameen: RabbitChat
  #项目版本
  version: v0.5
  #redis过期默认时间(秒)
  redisexpiretime: 3600
  #3des密钥
  des3key: IE37Ih9GfBM8oKajGMEGE37u
  #用户预设头像信息json
  userLogoJson: "{}"

#服务端口
server:
  port: 21010

#数据库连接
spring:
  datasource:
    #jdbc驱动程序
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://localhost:21001/rabbittest?characterEncoding=utf-8
    #数据库账号
    username: root
    #数据库密码
    password: Mh^F&e8bCH
  data:
    redis:
      #redis链接
      host: localhost
      #redis端口
      port: 21015
      #redis密码
      password: a&e8h^F&e8bCHM
      #读取redis超时时间(毫秒)
      timeout: 1000

#mybatis相关配置
mybatis:
  #mapper文件位置与格式
  mapper-locations: classpath:mapper/*.xml
  #设置实体类路径 其他位置的手动写注册吧
  type-aliases-package: cn.mikulink.rabbitchat.entity.db
  #设置日志 这样可以看到sql输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl












